// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Cocktail struct {
	ID           uuid.UUID
	Name         string
	Instructions []string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CocktailsEquipment struct {
	CocktailID  uuid.UUID
	EquipmentID uuid.UUID
}

type CocktailsIngredient struct {
	CocktailID   uuid.UUID
	IngredientID uuid.UUID
}

type Equipment struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Favorite struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FavoritesCocktail struct {
	FavoriteID uuid.UUID
	CocktailID uuid.UUID
}

type Ingredient struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
