// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (id, created_at, updated_at, name, api_key)
values (
        $1,
        $2,
        $3,
        $4,
        encode(sha256(random()::text::bytea), 'hex')
    )
returning id, name, created_at, updated_at, api_key
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
	)
	return i, err
}

const getFavoritesByUser = `-- name: GetFavoritesByUser :one
select id, user_id, created_at, updated_at
from favorites
where user_id = $1
`

func (q *Queries) GetFavoritesByUser(ctx context.Context, userID uuid.UUID) (Favorite, error) {
	row := q.db.QueryRowContext(ctx, getFavoritesByUser, userID)
	var i Favorite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
select id, name, created_at, updated_at, api_key
from users
where api_key = $1
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
	)
	return i, err
}
